# Generated by Django 4.2.20 on 2025-04-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_post_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='{user.username} post', max_length=50),
            preserve_default=False,
        ),
    ]
