# Generated by Django 5.1.7 on 2025-04-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_postratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postratings',
            name='user_rating',
        ),
    ]
