# Generated by Django 5.1.7 on 2025-04-08 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_mycustondict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustondict',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.game', to_field='game'),
        ),
    ]
